### ISSUE TITLE
Cannot load magrittr from a nonexistent .staging directory

### ISSUE THREAD

**Issue by peterhurford** [syberia/example.sy#1]
From my local:

``` R
> run("ex1")
Loading required package: objectdiff

Attaching package: ‘objectdiff’

The following objects are masked from ‘package:base’:

    as.environment, assign, environment, environment<-, get, ls,
    parent.env, parent.env<-, rm

Loading model: models/dev/example1
Beginning 1. import stage...
  Running 1. Import from R...
Error in diff(old_object, new_object) :
  cannot open file '/Users/peterhurford/.R/lockbox/.staging/magrittr/R/magrittr.rdb': No such file or directory
```

**Comment by robertzk** [comment]
Restart R and try again

On Monday, November 16, 2015, Peter Hurford notifications@github.com
wrote:

> From my local:
> 
> > run("ex1")Loading required package: objectdiff
> > Attaching package: ‘objectdiff’
> > The following objects are masked from ‘package:base’:
> 
> ```
> as.environment, assign, environment, environment<-, get, ls,
> parent.env, parent.env<-, rm
> ```
> 
> Loading model: models/dev/example1Beginning 1. import stage...
>   Running 1. Import from R...Error in diff(old_object, new_object) :
>   cannot open file '/Users/peterhurford/.R/lockbox/.staging/magrittr/R/magrittr.rdb': No such file or directory
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/syberia/example.sy/issues/1.

## 

-Robert Krzyzanowski

**Comment by peterhurford** [comment]
Problem persists after restart

**Comment by robertzk** [comment]
Thanks! I'll look into this

On Monday, November 16, 2015, Peter Hurford notifications@github.com
wrote:

> Problem persists after restart
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/syberia/example.sy/issues/1#issuecomment-157108947.

## 

-Robert Krzyzanowski

**Comment by peterhurford** [comment]
This is no longer an issue for me. :+1:

**Comment by peterhurford** [comment]
I got this again when trying on a new computer, but it disappeared after restarting R.  This seems like something we should at minimum warn people about, if not figure out a fix.

**Comment by robertzk** [comment]
@peterhurford Closing this.

**Comment by peterhurford** [comment]
@robertzk It will come up again if it's important. 👍
